-- =============================================
-- Migration: Add market_sentiments Table
-- Description: Creates table to store market sentiment analysis data
-- Author: System
-- Date: 2026-03-13
-- =============================================

-- Create market_sentiments table
CREATE TABLE IF NOT EXISTS market_sentiments (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    sentiment INT NOT NULL, -- 0=BEARISH, 1=NEUTRAL, 2=BULLISH
    sentimentscore DECIMAL(18,2) NOT NULL,
    volatilityindex DECIMAL(18,2) NOT NULL,
    marketbreadth DECIMAL(18,4) NOT NULL,
    indexperformance TEXT NOT NULL, -- JSON data
    sectorperformance TEXT NOT NULL, -- JSON data
    keyfactors TEXT NULL, -- JSON array
    createdat TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_market_sentiments PRIMARY KEY (id)
);

-- Create index on timestamp for efficient querying
CREATE INDEX IF NOT EXISTS ix_market_sentiments_timestamp 
    ON market_sentiments(timestamp DESC);

-- Create index on sentiment for filtering
CREATE INDEX IF NOT EXISTS ix_market_sentiments_sentiment 
    ON market_sentiments(sentiment);

-- Create index on createdat for historical queries
CREATE INDEX IF NOT EXISTS ix_market_sentiments_createdat 
    ON market_sentiments(createdat DESC);

-- Add check constraint for sentimentscore range
DO $$
BEGIN
IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'ck_market_sentiments_sentimentscore'
) THEN
    ALTER TABLE market_sentiments
    ADD CONSTRAINT ck_market_sentiments_sentimentscore
    CHECK (sentimentscore >= -100 AND sentimentscore <= 100);
END IF;
END $$;

-- Add check constraint for volatilityindex
DO $$
BEGIN
IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'ck_market_sentiments_volatilityindex'
) THEN
    ALTER TABLE market_sentiments
    ADD CONSTRAINT ck_market_sentiments_volatilityindex
    CHECK (volatilityindex >= 0 AND volatilityindex <= 100);
END IF;
END $$;

-- Add check constraint for marketbreadth
DO $$
BEGIN
IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'ck_market_sentiments_marketbreadth'
) THEN
    ALTER TABLE market_sentiments
    ADD CONSTRAINT ck_market_sentiments_marketbreadth
    CHECK (marketbreadth >= 0);
END IF;
END $$;

-- Add check constraint for sentiment enum values
DO $$
BEGIN
IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'ck_market_sentiments_sentiment'
) THEN
    ALTER TABLE market_sentiments
    ADD CONSTRAINT ck_market_sentiments_sentiment
    CHECK (sentiment IN (0,1,2));
END IF;
END $$;