-- =============================================
-- Migration: Add Strategy Signal and Performance Tables
-- =============================================

-- Create StrategySignals table
CREATE TABLE IF NOT EXISTS strategy_signals (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    instrument_id INT NOT NULL,
    strategy_type INT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    is_valid BOOLEAN NOT NULL,
    score INT NOT NULL,
    direction VARCHAR(10) NOT NULL,
    entry_price DECIMAL(18,4) NOT NULL,
    stop_loss DECIMAL(18,4) NOT NULL,
    target DECIMAL(18,4) NOT NULL,
    confidence DECIMAL(18,2) NOT NULL,
    risk_reward_ratio DECIMAL(8,2) NOT NULL,
    signals_json TEXT NOT NULL,
    metrics_json TEXT NOT NULL,
    explanation TEXT NULL,
    market_sentiments_id INT NULL,
    was_acted_upon BOOLEAN NOT NULL DEFAULT FALSE,
    related_trade_id INT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NULL,

    CONSTRAINT PK_strategy_signals PRIMARY KEY (id),

    CONSTRAINT FK_strategy_signals_instruments 
        FOREIGN KEY (instrument_id)
        REFERENCES instruments(id)
        ON DELETE CASCADE,

    CONSTRAINT FK_strategy_signals_market_sentiments 
        FOREIGN KEY (market_sentiments_id)
        REFERENCES market_sentiments(id)
        ON DELETE SET NULL,

    CONSTRAINT FK_strategy_signals_trades 
        FOREIGN KEY (related_trade_id)
        REFERENCES trades(id)
        ON DELETE SET NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_strategy_signals_lookup
ON strategy_signals(instrument_id, strategy_type, timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_strategy_signals_valid_score
ON strategy_signals(strategy_type, is_valid, score DESC);

CREATE INDEX IF NOT EXISTS idx_strategy_signals_timestamp
ON strategy_signals(timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_strategy_signals_acted
ON strategy_signals(was_acted_upon, expires_at);


-- Create StrategyPerformances table
CREATE TABLE IF NOT EXISTS strategy_performances (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    strategy_type INT NOT NULL,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    total_signals INT NOT NULL DEFAULT 0,
    valid_signals INT NOT NULL DEFAULT 0,
    signals_acted_upon INT NOT NULL DEFAULT 0,
    average_score DECIMAL(18,2) NOT NULL DEFAULT 0,
    average_confidence DECIMAL(18,2) NOT NULL DEFAULT 0,
    winning_trades INT NOT NULL DEFAULT 0,
    losing_trades INT NOT NULL DEFAULT 0,
    win_rate DECIMAL(18,2) NOT NULL DEFAULT 0,
    average_pnl DECIMAL(18,4) NOT NULL DEFAULT 0,
    total_pnl DECIMAL(18,4) NOT NULL DEFAULT 0,
    best_trade DECIMAL(18,4) NOT NULL DEFAULT 0,
    worst_trade DECIMAL(18,4) NOT NULL DEFAULT 0,
    average_risk_reward DECIMAL(8,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_strategy_performances PRIMARY KEY (id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_strategy_performances_lookup
ON strategy_performances(strategy_type, period_end DESC);

CREATE INDEX IF NOT EXISTS idx_strategy_performances_winrate
ON strategy_performances(win_rate DESC);

-- Constraints
ALTER TABLE strategy_signals
ADD CONSTRAINT CK_strategy_signals_score
CHECK (score >= 0 AND score <= 100);

ALTER TABLE strategy_signals
ADD CONSTRAINT CK_strategy_signals_confidence
CHECK (confidence >= 0 AND confidence <= 100);

ALTER TABLE strategy_signals
ADD CONSTRAINT CK_strategy_signals_direction
CHECK (direction IN ('BUY','SELL'));

ALTER TABLE strategy_performances
ADD CONSTRAINT CK_strategy_performances_win_rate
CHECK (win_rate >= 0 AND win_rate <= 100);