-- =============================================
-- Migration: Add portfolio manager phase 1 schema
-- Date: 2026-04-25
-- =============================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'user_profiles' AND column_name = 'preferred_budget'
  ) THEN
    ALTER TABLE user_profiles ADD COLUMN preferred_budget NUMERIC(18,2);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'user_profiles' AND column_name = 'preferred_risk_profile'
  ) THEN
    ALTER TABLE user_profiles ADD COLUMN preferred_risk_profile TEXT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'user_profiles' AND column_name = 'preferred_sectors'
  ) THEN
    ALTER TABLE user_profiles ADD COLUMN preferred_sectors JSONB NOT NULL DEFAULT '[]'::jsonb;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'user_profiles' AND column_name = 'preferred_themes'
  ) THEN
    ALTER TABLE user_profiles ADD COLUMN preferred_themes JSONB NOT NULL DEFAULT '[]'::jsonb;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'user_profiles' AND column_name = 'auto_rebalance_enabled'
  ) THEN
    ALTER TABLE user_profiles ADD COLUMN auto_rebalance_enabled BOOLEAN NOT NULL DEFAULT FALSE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS portfolio_manager_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  session_name TEXT NOT NULL,
  initial_capital NUMERIC(18,2) NOT NULL,
  risk_profile TEXT NOT NULL,
  preferred_sectors JSONB NOT NULL DEFAULT '[]'::jsonb,
  preferred_themes JSONB NOT NULL DEFAULT '[]'::jsonb,
  auto_rebalance_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  max_positions INT NOT NULL,
  timeframe_minutes INT NOT NULL,
  min_confidence INT NOT NULL,
  mode TEXT NOT NULL,
  status TEXT NOT NULL,
  last_provider TEXT,
  last_model TEXT,
  last_run_at TIMESTAMPTZ,
  next_run_at TIMESTAMPTZ,
  total_runs INT NOT NULL DEFAULT 0,
  allocated_capital NUMERIC(18,2) NOT NULL DEFAULT 0,
  realized_pnl NUMERIC(18,2) NOT NULL DEFAULT 0,
  unrealized_pnl NUMERIC(18,2) NOT NULL DEFAULT 0,
  win_rate_percent NUMERIC(8,4) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS portfolio_manager_trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES portfolio_manager_sessions(id) ON DELETE CASCADE,
  instrument_id INT NOT NULL REFERENCES instruments(id) ON DELETE RESTRICT,
  symbol TEXT NOT NULL,
  instrument_name TEXT NOT NULL,
  sector TEXT,
  strategy TEXT,
  direction TEXT NOT NULL,
  entry_price NUMERIC(18,4) NOT NULL,
  exit_price NUMERIC(18,4),
  current_price NUMERIC(18,4) NOT NULL,
  quantity INT NOT NULL,
  allocated_capital NUMERIC(18,2) NOT NULL DEFAULT 0,
  allocation_percent NUMERIC(8,4) NOT NULL DEFAULT 0,
  confidence NUMERIC(8,4) NOT NULL DEFAULT 0,
  stop_loss NUMERIC(18,4) NOT NULL DEFAULT 0,
  target NUMERIC(18,4) NOT NULL DEFAULT 0,
  pnl NUMERIC(18,2),
  pnl_percent NUMERIC(8,4),
  entry_reasoning TEXT NOT NULL,
  exit_reasoning TEXT,
  signals JSONB NOT NULL DEFAULT '[]'::jsonb,
  model_provider TEXT,
  model_name TEXT,
  status TEXT NOT NULL,
  opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_portfolio_manager_sessions_user_id
  ON portfolio_manager_sessions(user_id);

CREATE INDEX IF NOT EXISTS idx_portfolio_manager_sessions_user_status
  ON portfolio_manager_sessions(user_id, status);

CREATE INDEX IF NOT EXISTS idx_portfolio_manager_sessions_updated_at
  ON portfolio_manager_sessions(updated_at);

CREATE INDEX IF NOT EXISTS idx_portfolio_manager_trades_session_status
  ON portfolio_manager_trades(session_id, status);

CREATE INDEX IF NOT EXISTS idx_portfolio_manager_trades_instrument
  ON portfolio_manager_trades(instrument_id);

CREATE INDEX IF NOT EXISTS idx_portfolio_manager_trades_created_at
  ON portfolio_manager_trades(created_at);
