// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingSystem.Data;

#nullable disable

namespace TradingSystem.Data.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    partial class TradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradingSystem.Core.Models.AIModelVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<float>("AveragePredictionError")
                        .HasColumnType("real")
                        .HasColumnName("average_prediction_error");

                    b.Property<string>("ChangeLog")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change_log");

                    b.Property<string>("CheckpointPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checkpoint_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeprecatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deprecated_at");

                    b.Property<string>("DeprecationReason")
                        .HasColumnType("text")
                        .HasColumnName("deprecation_reason");

                    b.Property<string>("FeatureImportanceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_importance_json");

                    b.Property<string>("HyperparametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hyperparameters_json");

                    b.Property<string>("ImprovementNotes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("improvement_notes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<float>("MaxDrawdown")
                        .HasColumnType("real")
                        .HasColumnName("max_drawdown");

                    b.Property<string>("ModelFilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_file_path");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_type");

                    b.Property<float>("ProductionAccuracy")
                        .HasColumnType("real")
                        .HasColumnName("production_accuracy");

                    b.Property<float>("ProductionSharpeRatio")
                        .HasColumnType("real")
                        .HasColumnName("production_sharpe_ratio");

                    b.Property<float>("ProfitFactor")
                        .HasColumnType("real")
                        .HasColumnName("profit_factor");

                    b.Property<float>("SharpeRatio")
                        .HasColumnType("real")
                        .HasColumnName("sharpe_ratio");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("SuccessfulPredictions")
                        .HasColumnType("integer")
                        .HasColumnName("successful_predictions");

                    b.Property<decimal>("TotalPnL")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_pnl");

                    b.Property<int>("TotalPredictions")
                        .HasColumnType("integer")
                        .HasColumnName("total_predictions");

                    b.Property<float>("TrainingAccuracy")
                        .HasColumnType("real")
                        .HasColumnName("training_accuracy");

                    b.Property<int>("TrainingDatasetSize")
                        .HasColumnType("integer")
                        .HasColumnName("training_dataset_size");

                    b.Property<DateTimeOffset>("TrainingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("training_date");

                    b.Property<string>("TrainingDuration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("training_duration");

                    b.Property<float>("ValidationAccuracy")
                        .HasColumnType("real")
                        .HasColumnName("validation_accuracy");

                    b.Property<int>("ValidationDatasetSize")
                        .HasColumnType("integer")
                        .HasColumnName("validation_dataset_size");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.Property<float>("WinRate")
                        .HasColumnType("real")
                        .HasColumnName("win_rate");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_ai_model_versions_active");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_ai_model_versions_status");

                    b.HasIndex("Version", "ModelType")
                        .IsUnique()
                        .HasDatabaseName("idx_ai_model_versions_unique");

                    b.ToTable("ai_model_versions", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.FactorPerformanceTracking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<float>("LiquidityWeight")
                        .HasColumnType("real")
                        .HasColumnName("liquidity_weight");

                    b.Property<float>("MomentumAvgReturn")
                        .HasColumnType("real")
                        .HasColumnName("momentum_avg_return");

                    b.Property<int>("MomentumTradeCount")
                        .HasColumnType("integer")
                        .HasColumnName("momentum_trade_count");

                    b.Property<float>("MomentumWeight")
                        .HasColumnType("real")
                        .HasColumnName("momentum_weight");

                    b.Property<float>("MomentumWinRate")
                        .HasColumnType("real")
                        .HasColumnName("momentum_win_rate");

                    b.Property<float>("OverallSharpeRatio")
                        .HasColumnType("real")
                        .HasColumnName("overall_sharpe_ratio");

                    b.Property<float>("OverallWinRate")
                        .HasColumnType("real")
                        .HasColumnName("overall_win_rate");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<string>("RecommendedAdjustmentsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommended_adjustments_json");

                    b.Property<float>("RelativeStrengthWeight")
                        .HasColumnType("real")
                        .HasColumnName("relative_strength_weight");

                    b.Property<float>("RiskWeight")
                        .HasColumnType("real")
                        .HasColumnName("risk_weight");

                    b.Property<float>("SentimentAvgReturn")
                        .HasColumnType("real")
                        .HasColumnName("sentiment_avg_return");

                    b.Property<int>("SentimentTradeCount")
                        .HasColumnType("integer")
                        .HasColumnName("sentiment_trade_count");

                    b.Property<float>("SentimentWeight")
                        .HasColumnType("real")
                        .HasColumnName("sentiment_weight");

                    b.Property<float>("SentimentWinRate")
                        .HasColumnType("real")
                        .HasColumnName("sentiment_win_rate");

                    b.Property<float>("TotalTrades")
                        .HasColumnType("real")
                        .HasColumnName("total_trades");

                    b.Property<float>("TrendAvgReturn")
                        .HasColumnType("real")
                        .HasColumnName("trend_avg_return");

                    b.Property<int>("TrendTradeCount")
                        .HasColumnType("integer")
                        .HasColumnName("trend_trade_count");

                    b.Property<float>("TrendWeight")
                        .HasColumnType("real")
                        .HasColumnName("trend_weight");

                    b.Property<float>("TrendWinRate")
                        .HasColumnType("real")
                        .HasColumnName("trend_win_rate");

                    b.Property<float>("VolatilityWeight")
                        .HasColumnType("real")
                        .HasColumnName("volatility_weight");

                    b.HasKey("Id");

                    b.HasIndex("PeriodStart", "PeriodEnd")
                        .HasDatabaseName("idx_factor_performance_period");

                    b.ToTable("factor_performance_tracking", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.FeatureStore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FeatureCount")
                        .HasColumnType("integer")
                        .HasColumnName("feature_count");

                    b.Property<string>("FeatureVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("feature_version");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("features_json");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("symbol");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("FeatureVersion")
                        .HasDatabaseName("idx_feature_store_version");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("idx_feature_store_symbol");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_feature_store_timestamp");

                    b.HasIndex("InstrumentId", "Timestamp")
                        .HasDatabaseName("idx_feature_store_instrument_time");

                    b.ToTable("feature_store", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.FusionLearningConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Iteration")
                        .HasColumnType("integer")
                        .HasColumnName("iteration");

                    b.Property<decimal>("MinimumFusionScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("minimum_fusion_score");

                    b.Property<decimal>("NewsNegativeBoundary")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("news_negative_boundary");

                    b.Property<decimal>("NewsPositiveBoundary")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("news_positive_boundary");

                    b.Property<decimal>("NewsWeight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("news_weight");

                    b.Property<string>("PerformanceUnderThisConfigJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("performance_under_this_config_json");

                    b.Property<string>("PriorConfigJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("prior_config_json");

                    b.Property<string>("PriorPerformanceMetricsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("prior_performance_metrics_json");

                    b.Property<string>("ReasoningText")
                        .HasColumnType("text")
                        .HasColumnName("reasoning_text");

                    b.Property<string>("RiskAssessment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_assessment");

                    b.Property<DateTime?>("RolledBackAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rolled_back_at");

                    b.Property<decimal>("SectorWeight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("sector_weight");

                    b.Property<int>("SessionsAnalyzed")
                        .HasColumnType("integer")
                        .HasColumnName("sessions_analyzed");

                    b.Property<int>("SessionsCompletedUnderThisConfig")
                        .HasColumnType("integer")
                        .HasColumnName("sessions_completed_under_this_config");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TechnicalWeight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("technical_weight");

                    b.HasKey("Id");

                    b.HasIndex("AppliedAt")
                        .HasDatabaseName("idx_fusion_learning_config_applied_at");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_fusion_learning_config_created_at");

                    b.HasIndex("Iteration")
                        .IsUnique()
                        .HasDatabaseName("idx_fusion_learning_config_iteration");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_fusion_learning_config_status");

                    b.ToTable("fusion_learning_configs", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.IndicatorSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ADX")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("adx");

                    b.Property<decimal>("ATR")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("atr");

                    b.Property<decimal>("BollingerLower")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("bollinger_lower");

                    b.Property<decimal>("BollingerMiddle")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("bollinger_middle");

                    b.Property<decimal>("BollingerUpper")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("bollinger_upper");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EMAFast")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("ema_fast");

                    b.Property<decimal>("EMASlow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("ema_slow");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<decimal>("MacdHistogram")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("macd_histogram");

                    b.Property<decimal>("MacdLine")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("macd_line");

                    b.Property<decimal>("MacdSignal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("macd_signal");

                    b.Property<decimal>("MinusDI")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("minus_di");

                    b.Property<decimal>("PlusDI")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("plus_di");

                    b.Property<decimal>("RSI")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rsi");

                    b.Property<int>("TimeframeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("timeframe_minutes");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("VWAP")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("vwap");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("idx_indicator_snapshots_instrument");

                    b.HasIndex("InstrumentId", "TimeframeMinutes", "Timestamp")
                        .HasDatabaseName("idx_indicator_snapshots_lookup");

                    b.ToTable("indicator_snapshots", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.InstrumentPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("close");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("high");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("open");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timeframe");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_instrument_prices_timestamp");

                    b.HasIndex("InstrumentId", "Timeframe")
                        .HasDatabaseName("idx_instrument_prices_instrument_timeframe");

                    b.HasIndex("InstrumentId", "Timeframe", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("idx_instrument_prices_unique");

                    b.ToTable("instrument_prices", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.MarketCandle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("TimeframeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("timeframe_minutes");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("close");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("high");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("open");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id", "Timestamp", "TimeframeMinutes");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("idx_market_candles_instrument");

                    b.HasIndex("InstrumentId", "TimeframeMinutes", "Timestamp")
                        .HasDatabaseName("idx_market_candles_chart_query");

                    b.ToTable("market_candles", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.MarketSentiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IndexPerformance")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("index_performance");

                    b.Property<List<string>>("KeyFactors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("key_factors");

                    b.Property<decimal>("MacdHistogram")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("macd_histogram");

                    b.Property<decimal>("MarketBreadth")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("market_breadth");

                    b.Property<decimal>("MclellanOscillator")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("mclellan_oscillator");

                    b.Property<int>("NewHighs52W")
                        .HasColumnType("integer")
                        .HasColumnName("new_highs_52w");

                    b.Property<int>("NewLows52W")
                        .HasColumnType("integer")
                        .HasColumnName("new_lows_52w");

                    b.Property<decimal>("PriceVs20DMA")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("price_vs_20dma");

                    b.Property<decimal>("PriceVs50DMA")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("price_vs_50dma");

                    b.Property<decimal>("RSI")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("rsi");

                    b.Property<string>("SectorPerformance")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sector_performance");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sentiment");

                    b.Property<decimal>("SentimentScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("sentiment_score");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("VixVs20DMA")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("vix_vs_20dma");

                    b.Property<decimal>("VolatilityIndex")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("volatility_index");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_market_sentiments_created_at");

                    b.HasIndex("Sentiment")
                        .HasDatabaseName("idx_market_sentiments_sentiment");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_market_sentiments_timestamp");

                    b.ToTable("market_sentiments", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.NewsArticle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headline");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sentiment");

                    b.Property<decimal>("SentimentScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("sentiment_score");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("idx_news_articles_external_id");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("idx_news_articles_published_at");

                    b.HasIndex("Source")
                        .HasDatabaseName("idx_news_articles_source");

                    b.ToTable("news_articles", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.NewsImpact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint")
                        .HasColumnName("article_id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<decimal>("ImpactScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("impact_score");

                    b.Property<int?>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<int?>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("idx_news_impacts_article_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_news_impacts_created_at");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("idx_news_impacts_instrument_id");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("idx_news_impacts_sector_id");

                    b.ToTable("news_impacts", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.NewsKeyword", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint")
                        .HasColumnName("article_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("keyword");

                    b.Property<decimal>("RelevanceScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("relevance_score");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("idx_news_keywords_article_id");

                    b.HasIndex("Keyword")
                        .HasDatabaseName("idx_news_keywords_keyword");

                    b.ToTable("news_keywords", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.PortfolioManagerSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AllocatedCapital")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("allocated_capital");

                    b.Property<bool>("AutoRebalanceEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_rebalance_enabled");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("InitialCapital")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("initial_capital");

                    b.Property<string>("LastModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_model");

                    b.Property<string>("LastProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_provider");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<int>("MaxPositions")
                        .HasColumnType("integer")
                        .HasColumnName("max_positions");

                    b.Property<int>("MinConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("min_confidence");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<string>("PreferredSectors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preferred_sectors");

                    b.Property<string>("PreferredThemes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preferred_themes");

                    b.Property<decimal>("RealizedPnl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("realized_pnl");

                    b.Property<string>("RiskProfile")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("risk_profile");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("session_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TimeframeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("timeframe_minutes");

                    b.Property<int>("TotalRuns")
                        .HasColumnType("integer")
                        .HasColumnName("total_runs");

                    b.Property<decimal>("UnrealizedPnl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unrealized_pnl");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WinRatePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("win_rate_percent");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("idx_portfolio_manager_sessions_updated_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_portfolio_manager_sessions_user_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_portfolio_manager_sessions_user_status");

                    b.ToTable("portfolio_manager_sessions", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.PortfolioManagerTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AllocatedCapital")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("allocated_capital");

                    b.Property<decimal>("AllocationPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("allocation_percent");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_price");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("entry_price");

                    b.Property<string>("EntryReasoning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entry_reasoning");

                    b.Property<decimal?>("ExitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("exit_price");

                    b.Property<string>("ExitReasoning")
                        .HasColumnType("text")
                        .HasColumnName("exit_reasoning");

                    b.Property<bool?>("FusionDirectionVeto")
                        .HasColumnType("boolean")
                        .HasColumnName("fusion_direction_veto");

                    b.Property<string>("FusionEvidence")
                        .HasColumnType("text")
                        .HasColumnName("fusion_evidence");

                    b.Property<bool?>("FusionIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("fusion_included");

                    b.Property<decimal?>("FusionNewsSignal")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("fusion_news_signal");

                    b.Property<decimal?>("FusionScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("fusion_score");

                    b.Property<decimal?>("FusionSectorSignal")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("fusion_sector_signal");

                    b.Property<decimal?>("FusionTechnicalSignal")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("fusion_technical_signal");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<string>("InstrumentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instrument_name");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_provider");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<decimal?>("Pnl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("pnl");

                    b.Property<decimal?>("PnlPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("pnl_percent");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sector");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<string>("Signals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("signals");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("stop_loss");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("strategy");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("Target")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("target");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_portfolio_manager_trades_created_at");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("idx_portfolio_manager_trades_instrument");

                    b.HasIndex("SessionId", "Status")
                        .HasDatabaseName("idx_portfolio_manager_trades_session_status");

                    b.ToTable("portfolio_manager_trades", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.PortfolioPerformanceHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActiveFusionLearningConfigIteration")
                        .HasColumnType("integer")
                        .HasColumnName("active_fusion_learning_config_iteration");

                    b.Property<decimal>("AverageFusionScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("average_fusion_score");

                    b.Property<decimal>("AverageHoldDays")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("average_hold_days");

                    b.Property<decimal>("AverageHoldEfficiency")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("average_hold_efficiency");

                    b.Property<int>("LosingTrades")
                        .HasColumnType("integer")
                        .HasColumnName("losing_trades");

                    b.Property<decimal>("MaxDrawdown")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("max_drawdown");

                    b.Property<decimal>("ProfitFactor")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("profit_factor");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<decimal>("SharpeRatio")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("sharpe_ratio");

                    b.Property<decimal>("TotalPnL")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_pnl");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("integer")
                        .HasColumnName("total_trades");

                    b.Property<decimal>("VetoRejectionRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("veto_rejection_rate");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("win_rate");

                    b.Property<int>("WinningTrades")
                        .HasColumnType("integer")
                        .HasColumnName("winning_trades");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("idx_portfolio_perf_history_recorded_at");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_portfolio_perf_history_session_id");

                    b.ToTable("portfolio_performance_histories", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.Recommendation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("entry_price");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExplanationText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation_text");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("OptionStrike")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("option_strike");

                    b.Property<string>("OptionType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("option_type");

                    b.Property<string>("ReasoningPoints")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasoning_points");

                    b.Property<decimal>("RiskRewardRatio")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("risk_reward_ratio");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("stop_loss");

                    b.Property<decimal>("Target")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("target");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Confidence", "Timestamp")
                        .HasDatabaseName("idx_recommendations_confidence");

                    b.HasIndex("InstrumentId", "Timestamp")
                        .HasDatabaseName("idx_recommendations_instrument");

                    b.HasIndex("IsActive", "Timestamp")
                        .HasDatabaseName("idx_recommendations_active");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.ScanSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ATR")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("atr");

                    b.Property<int>("AdxScore")
                        .HasColumnType("integer")
                        .HasColumnName("adx_score");

                    b.Property<string>("Bias")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("bias");

                    b.Property<int>("BollingerScore")
                        .HasColumnType("integer")
                        .HasColumnName("bollinger_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EmaVwapScore")
                        .HasColumnType("integer")
                        .HasColumnName("ema_vwap_score");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<decimal>("LastClose")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("last_close");

                    b.Property<string>("MarketState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("market_state");

                    b.Property<int>("RsiScore")
                        .HasColumnType("integer")
                        .HasColumnName("rsi_score");

                    b.Property<int>("SetupScore")
                        .HasColumnType("integer")
                        .HasColumnName("setup_score");

                    b.Property<int>("StructureScore")
                        .HasColumnType("integer")
                        .HasColumnName("structure_score");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("VolumeScore")
                        .HasColumnType("integer")
                        .HasColumnName("volume_score");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("idx_scan_snapshots_instrument");

                    b.HasIndex("InstrumentId", "Timestamp")
                        .HasDatabaseName("idx_scan_snapshots_lookup");

                    b.HasIndex("SetupScore", "Timestamp")
                        .HasDatabaseName("idx_scan_snapshots_score");

                    b.ToTable("scan_snapshots", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_sectors_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_sectors_name");

                    b.ToTable("sectors", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.TradeOutcome", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ActualReturn")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_return");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("entry_price");

                    b.Property<DateTimeOffset>("EntryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_time");

                    b.Property<decimal?>("ExitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("exit_price");

                    b.Property<DateTimeOffset?>("ExitTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exit_time");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<bool?>("IsSuccessful")
                        .HasColumnType("boolean")
                        .HasColumnName("is_successful");

                    b.Property<string>("LearningTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("learning_tags");

                    b.Property<string>("MarketRegimeAtEntry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("market_regime_at_entry");

                    b.Property<string>("MetaFactorsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_factors_json");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("model_version");

                    b.Property<float>("PredictedReturn")
                        .HasColumnType("real")
                        .HasColumnName("predicted_return");

                    b.Property<float>("PredictedRiskScore")
                        .HasColumnType("real")
                        .HasColumnName("predicted_risk_score");

                    b.Property<float>("PredictedSuccessProbability")
                        .HasColumnType("real")
                        .HasColumnName("predicted_success_probability");

                    b.Property<float?>("PredictionAccuracyScore")
                        .HasColumnType("real")
                        .HasColumnName("prediction_accuracy_score");

                    b.Property<float?>("PredictionError")
                        .HasColumnType("real")
                        .HasColumnName("prediction_error");

                    b.Property<decimal?>("ProfitLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("profit_loss");

                    b.Property<decimal?>("ProfitLossPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("profit_loss_percent");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<float>("RegimeConfidence")
                        .HasColumnType("real")
                        .HasColumnName("regime_confidence");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sector");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("strategy");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("symbol");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EntryTime")
                        .HasDatabaseName("idx_trade_outcomes_entry_time");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("idx_trade_outcomes_instrument");

                    b.HasIndex("ModelVersion")
                        .HasDatabaseName("idx_trade_outcomes_model_version");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_trade_outcomes_status");

                    b.HasIndex("MarketRegimeAtEntry", "IsSuccessful")
                        .HasDatabaseName("idx_trade_outcomes_regime_success");

                    b.ToTable("trade_outcomes", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.TradeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ATRAtEntry")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("atr_at_entry");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<string>("EntryIndicatorsJson")
                        .HasColumnType("text");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("entry_price");

                    b.Property<string>("EntryReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entry_reason");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_time");

                    b.Property<string>("ExitIndicatorsJson")
                        .HasColumnType("text");

                    b.Property<decimal?>("ExitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("exit_price");

                    b.Property<string>("ExitReason")
                        .HasColumnType("text")
                        .HasColumnName("exit_reason");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exit_time");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<decimal?>("OptionEntryPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("option_entry_price");

                    b.Property<decimal?>("OptionExitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("option_exit_price");

                    b.Property<decimal?>("OptionStrike")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("option_strike");

                    b.Property<string>("OptionSymbol")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("option_symbol");

                    b.Property<decimal>("PnL")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("pnl");

                    b.Property<decimal>("PnLPercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("pnl_percent");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("stop_loss");

                    b.Property<decimal>("Target")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("target");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trade_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EntryTime")
                        .HasDatabaseName("idx_trades_entry_time");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("idx_trades_instrument");

                    b.HasIndex("State")
                        .HasDatabaseName("idx_trades_state");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.TradingInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultTradingMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("default_trading_mode");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("exchange");

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("isin");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("industry");

                    b.Property<string>("InstrumentKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("instrument_key");

                    b.Property<string>("InstrumentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("instrument_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDerivativesEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_derivatives_enabled");

                    b.Property<int>("LotSize")
                        .HasColumnType("integer")
                        .HasColumnName("lot_size");

                    b.Property<decimal?>("MarketCap")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("market_cap");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("TickSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tick_size");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentKey")
                        .IsUnique()
                        .HasDatabaseName("idx_instruments_key");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_instruments_active");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("idx_instruments_sector_id");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("idx_instruments_symbol");

                    b.ToTable("instruments", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AutoRebalanceEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_rebalance_enabled");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<decimal?>("PreferredBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preferred_budget");

                    b.Property<string>("PreferredRiskProfile")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("preferred_risk_profile");

                    b.Property<string>("PreferredSectors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preferred_sectors");

                    b.Property<string>("PreferredThemes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preferred_themes");

                    b.Property<DateTime?>("TokenIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_issued_at");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<string>("UpstoxAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("upstox_access_token");

                    b.Property<string>("UpstoxRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("upstox_refresh_token");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedOn")
                        .HasDatabaseName("idx_user_profiles_updated_on");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_user_profiles_user_id");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("TradingSystem.Core.Models.FeatureStore", b =>
                {
                    b.HasOne("TradingSystem.Core.Models.TradingInstrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.IndicatorSnapshot", b =>
                {
                    b.HasOne("TradingSystem.Core.Models.TradingInstrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.InstrumentPrice", b =>
                {
                    b.HasOne("TradingSystem.Core.Models.TradingInstrument", "Instrument")
                        .WithMany("Prices")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.MarketCandle", b =>
                {
                    b.HasOne("TradingSystem.Core.Models.TradingInstrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.NewsImpact", b =>
                {
                    b.HasOne("TradingSystem.Core.Models.NewsArticle", "Article")
                        .WithMany("Impacts")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingSystem.Core.Models.TradingInstrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TradingSystem.Core.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Article");

                    b.Navigation("Instrument");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.NewsKeyword", b =>
                {
                    b.HasOne("TradingSystem.Core.Models.NewsArticle", "Article")
                        .WithMany("Keywords")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.PortfolioManagerTrade", b =>
                {
                    b.HasOne("TradingSystem.Core.Models.TradingInstrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradingSystem.Core.Models.PortfolioManagerSession", "Session")
                        .WithMany("Trades")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.PortfolioPerformanceHistory", b =>
                {
                    b.HasOne("TradingSystem.Core.Models.PortfolioManagerSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.Recommendation", b =>
                {
                    b.HasOne("TradingSystem.Core.Models.TradingInstrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.ScanSnapshot", b =>
                {
                    b.HasOne("TradingSystem.Core.Models.TradingInstrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.TradeOutcome", b =>
                {
                    b.HasOne("TradingSystem.Core.Models.TradingInstrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.TradeRecord", b =>
                {
                    b.HasOne("TradingSystem.Core.Models.TradingInstrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.TradingInstrument", b =>
                {
                    b.HasOne("TradingSystem.Core.Models.Sector", "Sector")
                        .WithMany("Instruments")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.NewsArticle", b =>
                {
                    b.Navigation("Impacts");

                    b.Navigation("Keywords");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.PortfolioManagerSession", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.Sector", b =>
                {
                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("TradingSystem.Core.Models.TradingInstrument", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
