/*
  # Add news ingestion phase 2 tables

  1. Changes
    - Create news_articles table
    - Create news_keywords table
    - Create news_impacts table
    - Add indexes for recency and lookup
*/

CREATE TABLE IF NOT EXISTS news_articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id TEXT NOT NULL,
  source TEXT NOT NULL,
  url TEXT NOT NULL,
  headline TEXT NOT NULL,
  summary TEXT NOT NULL,
  published_at TIMESTAMPTZ NOT NULL,
  ingested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sentiment TEXT NOT NULL,
  sentiment_score NUMERIC(8,4) NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_news_articles_external_id
  ON news_articles(external_id);

CREATE INDEX IF NOT EXISTS idx_news_articles_published_at
  ON news_articles(published_at DESC);

CREATE INDEX IF NOT EXISTS idx_news_articles_source
  ON news_articles(source);

CREATE TABLE IF NOT EXISTS news_keywords (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id BIGINT NOT NULL REFERENCES news_articles(id) ON DELETE CASCADE,
  keyword TEXT NOT NULL,
  relevance_score NUMERIC(8,4) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_news_keywords_article_id
  ON news_keywords(article_id);

CREATE INDEX IF NOT EXISTS idx_news_keywords_keyword
  ON news_keywords(keyword);

CREATE TABLE IF NOT EXISTS news_impacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id BIGINT NOT NULL REFERENCES news_articles(id) ON DELETE CASCADE,
  instrument_id INT REFERENCES instruments(id) ON DELETE SET NULL,
  sector_id INT REFERENCES sectors(id) ON DELETE SET NULL,
  direction TEXT NOT NULL,
  impact_score NUMERIC(8,4) NOT NULL DEFAULT 0,
  confidence NUMERIC(8,4) NOT NULL DEFAULT 0,
  rationale TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_news_impacts_article_id
  ON news_impacts(article_id);

CREATE INDEX IF NOT EXISTS idx_news_impacts_instrument_id
  ON news_impacts(instrument_id);

CREATE INDEX IF NOT EXISTS idx_news_impacts_sector_id
  ON news_impacts(sector_id);

CREATE INDEX IF NOT EXISTS idx_news_impacts_created_at
  ON news_impacts(created_at DESC);
